version: '3.3'

services:
  mysql:
    build:
        context: ./
        dockerfile: mysql.dockerfile
    volumes:
      - ./.data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'root'

  nginx:
    build:
      context: ./
      dockerfile: nginx.dockerfile
    ports:
      - "13080:80"
    volumes:
      - ./.config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./.config/nginx/conf.d:/etc/nginx/conf.d
      - ./.data/nginx:/var/log/nginx

      - ./html:/var/www/html
    links:
      - php
  php:
    build:
      context: ./
      dockerfile: php.dockerfile
      args:
        - PHP_GD=true
    depends_on:
      - mysql
    links:
      - mysql
    volumes:
      - ./.config/php/config.d:/usr/local/etc/php/config.d
      - ./.data/composer:/root/.composer

      - ./html:/var/www/html
